---
name: kblackbox
version: 17.08.1
summary: Blackbox Logic Game
description: KBlackbox is a game of hide and seek played on a grid of boxes where
    the computer has hidden several balls. The position of the hidden balls can be
    deduced by shooting beams into the box.
confinement: strict
grade: stable
apps:
    kblackbox:
        command: kf5-launch kblackbox
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kblackbox:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libkf5kdegames-dev
        - libkf5kdelibs4support-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kblackbox-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
